apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.ext.sdkVersion

    lintOptions {
        abortOnError false
        checkAllWarnings false
        checkReleaseBuilds false
        lintConfig file("path/to/custom/lint.xml")
    }

    testOptions {
        unitTests.all {
            enabled = false
            ignoreFailures = true
        }
    }

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.sdkVersion
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidx_appcompat_version}"

}
